// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/instagram/staged-upload": {
    params: {};
  };
  "/webhooks/app/scopes_update": {
    params: {};
  };
  "/api/delete-instagram-data": {
    params: {};
  };
  "/webhooks/app/uninstalled": {
    params: {};
  };
  "/api/cron/refresh": {
    params: {};
  };
  "/auth/login": {
    params: {};
  };
  "/instagram": {
    params: {};
  };
  "/instagram/callback": {
    params: {};
  };
  "/auth/*": {
    params: {
      "*": string;
    };
  };
  "/app": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/api/instagram/staged-upload" | "/webhooks/app/scopes_update" | "/api/delete-instagram-data" | "/webhooks/app/uninstalled" | "/api/cron/refresh" | "/auth/login" | "/instagram" | "/instagram/callback" | "/auth/*" | "/app";
  };
  "routes/api.instagram.staged-upload.tsx": {
    id: "routes/api.instagram.staged-upload";
    page: "/api/instagram/staged-upload";
  };
  "routes/webhooks.app.scopes_update.tsx": {
    id: "routes/webhooks.app.scopes_update";
    page: "/webhooks/app/scopes_update";
  };
  "routes/api.delete-instagram-data.tsx": {
    id: "routes/api.delete-instagram-data";
    page: "/api/delete-instagram-data";
  };
  "routes/webhooks.app.uninstalled.tsx": {
    id: "routes/webhooks.app.uninstalled";
    page: "/webhooks/app/uninstalled";
  };
  "routes/api.cron.refresh.tsx": {
    id: "routes/api.cron.refresh";
    page: "/api/cron/refresh";
  };
  "routes/auth.login/route.tsx": {
    id: "routes/auth.login";
    page: "/auth/login";
  };
  "routes/instagram.tsx": {
    id: "routes/instagram";
    page: "/instagram" | "/instagram/callback";
  };
  "routes/instagram.callback.tsx": {
    id: "routes/instagram.callback";
    page: "/instagram/callback";
  };
  "routes/_index/route.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/auth.$.tsx": {
    id: "routes/auth.$";
    page: "/auth/*";
  };
  "routes/app.tsx": {
    id: "routes/app";
    page: "/app";
  };
  "routes/app._index.tsx": {
    id: "routes/app._index";
    page: "/app";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/api.instagram.staged-upload": typeof import("./app/routes/api.instagram.staged-upload.tsx");
  "routes/webhooks.app.scopes_update": typeof import("./app/routes/webhooks.app.scopes_update.tsx");
  "routes/api.delete-instagram-data": typeof import("./app/routes/api.delete-instagram-data.tsx");
  "routes/webhooks.app.uninstalled": typeof import("./app/routes/webhooks.app.uninstalled.tsx");
  "routes/api.cron.refresh": typeof import("./app/routes/api.cron.refresh.tsx");
  "routes/auth.login": typeof import("./app/routes/auth.login/route.tsx");
  "routes/instagram": typeof import("./app/routes/instagram.tsx");
  "routes/instagram.callback": typeof import("./app/routes/instagram.callback.tsx");
  "routes/_index": typeof import("./app/routes/_index/route.tsx");
  "routes/auth.$": typeof import("./app/routes/auth.$.tsx");
  "routes/app": typeof import("./app/routes/app.tsx");
  "routes/app._index": typeof import("./app/routes/app._index.tsx");
};